#' Make and save plots with \code{\link{lavaanPlot::lavaanPlot}}
#'
#' Saves a Structural Equation Model (SEM) plot generated by \code{\link{lavaanPlot::lavaanPlot}}.
#' The function handles intermediate steps, including exporting the plot to SVG and converting to PNG.
#'
#' @name saveLavaanPlot
#' @title Save Lavaan Plot
#' @docType package
#' @param fit A fitted \code{\link{lavaan::lavaan}} SEM model object (e.g., created using \code{cfa()} or \code{sem()}).
#' @param filePath A character string with the path to save the plot, including the file name and extension (e.g., "path/to/file.png").
#' @param coefs Logical. Whether to display path coefficients. Default is \code{TRUE}.
#' @param stand Logical. Whether to use standardized coefficients. Default is \code{TRUE}.
#' @param sig Numeric. The significance level to display. Default is \code{0.05}.
#' @param width Numeric. Width of the plot in pixels. Default is \code{1000}.
#' @param stars Character. If \code{"regress"}, significant coefficients are marked with stars. Default is \code{"regress"}.
#' @return A plot saved to the specified file path of the SEM model made by \code{\link{lavaan::lavaan}}.
#' @author Jasmijn Bazen \email{j.l.bazen@students.uu.nl}
#' @export
#'
#' @importFrom DiagrammeRsvg export_svg
#' @importFrom rsvg rsvg_png
#' @importFrom lavaanPlot lavaanPlot
#'
#' @examples
#' \dontrun{
#' Save_LavaanPlot(fit = SEMModel1,
#'                 filePath = "path/to/your/SEMModel.png",
#'                 coefs = TRUE,
#'                 stand = TRUE,
#'                 sig = 0.05,
#'                 stars = "regress",
#'                 width = 1000)
#' }
#'
# Function to fit the SEM model, generate the plot, and save it
#' @return A saved plot of the SEM model as a PNG file.
#'
#' @seealso \link{lavaanPlot}, \link{lavaan}
#'
#'
saveLavaanPlot <- function(fit, filePath, coefs = TRUE, stand = TRUE, sig = 0.05, stars = "regress", width = 1000) {

  # Validate the input model
  if (!inherits(fit, "lavaan")) {
    stop("The 'fit' argument must be a valid lavaan model object.")
  }
  if (!grepl("\\.png$", filePath)) {
    stop("The 'filePath' must end with '.png'.")
  }

  # Ensure the target directory exists
  dir_path <- dirname(filePath)
  if (!dir.exists(dir_path)) {
    cat("The directory", dir_path, "does not exist. Creating it now.\n")
    dir.create(dir_path, recursive = TRUE)
  }

  # Generate the SEM plot using explicit import
  sem_plot <- lavaanPlot::lavaanPlot(
    model = fit,
    coefs = coefs,
    stand = stand,
    sig   = sig,
    stars = stars
  )

  # Save as .svg and convert to .png
  svg_output <- DiagrammeRsvg::export_svg(sem_plot)
  svg_file <- tempfile(fileext = ".svg")
  writeLines(svg_output, svg_file)

  rsvg::rsvg_png(svg_file, filePath)

  # Inform user of saved file location
  cat("File saved to:", normalizePath(filePath), "\n")

  # Render the plot to the console
  cat("Rendering the plot to the console...\n")
  base::return(sem_plot)

}
